name: karee
description: Another way to build Flutter applications for mobile, web and desktop using Karee Architecture.
version: 2.2.3+5
homepage: https://github.com/ChamplainLeCode/karee
repository: https://github.com/ChamplainLeCode/karee
issue_tracker: https://github.com/ChamplainLeCode/karee/issues
report_issue: https://github.com/ChamplainLeCode/karee/issues/new

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  karee_inject: ^1.0.3+2
  yaml: ^3.1.1

dev_dependencies:
  mockito: any
  build_runner: any
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
flutter:
  assets:
    - assets/